config/routes.rb
Nl::Application.routes.draw do

	get "/home" => "pages#home", :as => :home
  get "/about" => "pages#about", :as => :about
  get "/team" => "pages#team", :as => :team

	get "/search" => "recipes#search", :as => :recipe_search  
	get "/recipes/:id/consume" => "recipes#consume", :as => :consume_recipe
	get "/remove_log_item/:lrid" => "users#remove_log_item", :as => :delete_logged_recipe
	resources :ingredients, :only => [:index, :show, :new, :create]
	resources :users
	resources :recipes
	get "/ingsearch" => "ingredients#search", :as => :ingredient_search
	get '/recipes/:id/ing/:ingredient_id' => "recipes#addingredient", :as => :ingredient_add
	get '/signup', :to => 'users#new'
	get '/signin', :to => 'sessions#new'
	post '/signin', :to => 'sessions#create'
	get '/signout', :to => 'sessions#destroy'
  match '/profile', :to => 'users#profile'
	root :to => "pages#home"
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
	belongs_to :creator, :class_name => "User"
	has_many :log_recipe

	has_many :recipe_ingredient_joins

	has_many :ingredients,
		:through => :recipe_ingredient_joins

	validates :name,
		:presence => true

	validates :serving_size,
		:presence => true

	def add_ingredient(i)
		self.ingredients << i
	end

	def add_ingredients(i)
		i.each do |ing|
			add_ingredient(ing)
		end
	end

	def self.search(search)
      if search
        find(:all, :conditions => ['name LIKE ?', "%#{search}%"], :order => "name ASC")
      else
        find(:all)
      end
    end


end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
	
	before_filter :redirect_if_not_signed_in, :except => :index
	
	def index
		@recent_recipes = Recipe.order("created_at DESC").limit(10)
		@title = "Recipes"
	end


	def new
		@title = "Create recipe"
		@recipe = Recipe.new
	end
	
     def show
		@recipe = Recipe.find(params[:id])
		@title = @recipe.name
		
      respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @recipe }
          end
    end		

	def consume
		@r = Recipe.find(params[:id])
		current_user.consume_recipe(@r)
		redirect_to profile_path
	end

	def create
		@r = Recipe.create(params[:recipe])
		if(@r.save)
			redirect_to @r
		else
			flash.now[:error] = "You had an error creating your recipe"
			@title = "Create recipe"
			@recipe = @r
			render 'new'
		end
	end

	def search
		render :partial => "search_results", :locals => {:recipes => Recipe.search(params[:q])}
	end


	def edit
		@recipe = Recipe.find(params[:id])
		@title = "Edit #{@recipe.name}"
	end


	def addingredient
		@recipe = Recipe.find(params[:id])
		@ing = Ingredient.find(params[:ingredient_id])
		unless @ing.nil?
			@recipe.ingredients << @ing	
		end
		redirect_to edit_recipe_path(@recipe)
	end

end

app/helpers/recipes_helper.rb
module RecipesHelper
    def recipe_params
		params[:recipe].slice(:name, :serving_size, :creator_id)
	end
end

app/views/recipes/_recipe_form.html.erb
<%= form_for(recipe) do |f| %>


			<div class = "field" >
				<%= f.label :name %><br />
				<%= f.text_field :name %>
			</div>
			<div class = "field" >
				<%= f.label :serving_size %><br />
				<%= f.text_field :serving_size %>
			</div>
			

			<div class = "actions" >
				<%= f.submit "Create recipe", :class => 'btn btn-primary'%>
				
			</div>
		<%end%>

app/views/recipes/_search_results.html.erb
<h2>Search Results</h2>
	<table class ="table table-striped">
		<thead>
		<tr>
		<th></th>
		<th></th>
		<th></th>
		<th></th>
		</tr>
		</thead>
		<%= "No recipes to display" if recipes.empty? %>
		<% recipes.each do |r| %>
		<tr>
		<td><%= r.name.titleize %></td>

<td><%= link_to "View Item", recipe_path(r), :class => "btn btn-primary btn-mini" %></td>
<td><%= link_to "Consume", consume_recipe_path(r), :class => "btn btn-success btn-mini" %></td>



		</tr>
		<% end %>
		</table>

app/views/recipes/new.html.erb
<div class = "row">
<div class = "center span6 middle offset5">
<div class = "hero-unit">


<h2>Create a new Recipe</h2>

<%= render :partial => "recipe_form", :locals => {:recipe => @recipe} %>

</div>
</div>
</div>

app/views/recipes/show.html.erb
<h1><%= @recipe.name.titleize %></h1>
<br>
<br>
<div class="row-fluid">
    <div class="span12">
        <div class ="hero-unit">
        <h2>Recipes <%= link_to "Consume", consume_recipe_path(@recipe), :class => 'btn btn-success pull-right' %><br>
        <%= link_to "Add Ingredient", root_path, :class => 'btn btn-success pull-right' %></h2>
        
        <table class ="table table-striped">
        <thead>
	        <tr>
	        <th> </th>
          	</tr>
        </thead>
        
        <%  @recipe.ingredients.each do |ingredient| %>
         <tr>
           <td><%= link_to ingredient.name.titleize, ingredient %></td>
        </tr>
<% end %>
</table>

        </div>
    </div>
</div>