config/routes.rb
Nl::Application.routes.draw do

	get "/home" => "pages#home", :as => :home
  get "/about" => "pages#about", :as => :about
  get "/team" => "pages#team", :as => :team

	get "/search" => "recipes#search", :as => :recipe_search  
	get "/recipes/:id/consume" => "recipes#consume", :as => :consume_recipe
	get "/remove_log_item/:lrid" => "users#remove_log_item", :as => :delete_logged_recipe
	resources :ingredients, :only => [:index, :show, :new, :create]
	resources :users
	resources :recipes
	get "/ingsearch" => "ingredients#search", :as => :ingredient_search
	get '/recipes/:id/ing/:ingredient_id' => "recipes#addingredient", :as => :ingredient_add
	get '/signup', :to => 'users#new'
	get '/signin', :to => 'sessions#new'
	post '/signin', :to => 'sessions#create'
	get '/signout', :to => 'sessions#destroy'
  match '/profile', :to => 'users#profile'
	root :to => "pages#home"
end

app/models/user.rb
require 'digest'
class User < ActiveRecord::Base

# accessor methods
	attr_accessor :password
	attr_accessible :name, :email, :password, :password_confirmation

# foreign key relations
	has_many :ingredients, 
		:foreign_key => "creator_id"
	
	has_many :recipes, 
		:foreign_key => "creator_id"
	
	has_many :logs
	
	has_many :recently_consumed_ingredients,
		:through => :logs,
		:class_name => "Ingredient",
		:conditions => ['logs.created_at > ?', 7.days.ago],
		:source => :ingredient,
		:foreign_key => "ingredient_id"
	
	has_many :consumed_ingredients, 
		:class_name => "Ingredient", 
		:through => :logs,
		:source => :ingredient

	has_many :log_recipes

	has_many :consumed_recipes, 
		:class_name => "Recipe",
		:through => :log_recipes,
		:source => :recipe
	

# validations
	validates :name, 
		:presence => true
	
	validates :email, 
		:presence => true,
		:format=> { :with => /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
		:uniqueness => {:case_sensitive => false }

	validates :password, 
		:presence => true,
		:confirmation => true,
		:length => {:minimum => 6},
		:if => :save_password?

	validates :password_confirmation, 
		:presence => true,
		:if => :save_password?


	def consume_recipe(r)
		self.consumed_recipes << r
		last = self.log_recipes.order("id desc").limit(1).first
		r.ingredients.each do |i|
			self.logs.create(:ingredient_id => i.id, :servings => 1, :date => Time.now, :log_recipe_id => last.id)
		end
	end

# callbacks
	before_save :encrypt_password

# methods
	def has_password?(sub_pwd)
		encrypted_password == encrypt(sub_pwd)
	end

	def self.authenticate(email, submitted_password)
		user = find_by_email(email)
		return nil if user.nil?
		return user if user.has_password?(submitted_password)
	end

	def self.authenticate_with_salt(id, cookie_salt)
		user = User.find_by_id(id)
		(user && user.salt == cookie_salt) ? user : nil
	end


	def getnuts
		nuts = {}
		nut_un = User.recently_consumed_nutritions(self.id)

		nut_un.each do |t|
			nuts[t[0].sub(" ", "_").to_sym] = t[1] * 1000
		end

		["Calories", "Protein", "Carbs", "Fiber", "Trans_Fat", "Fat", "Vitamin_B6", "Vitamin_B12", "Vitamin_C", "Vitamin_D", "Calcium", "Potassium", "Sodium"].each do |s|
			nuts[s.to_sym] = 0 unless nuts.include? s.to_sym
		end
    return nuts      

	end


	def self.recently_consumed_nutritions(id)
		self.connection.execute(sanitize_sql(["select n.name, sum(n.quantity) from nutritions n inner join ingredients i on n.ingredient_id = i.id inner join logs l on l.ingredient_id = i.id inner join users u on u.id = l.user_id where u.id=? and l.created_at > ? group by n.name", id, 1.day.ago]))
	
	end
	
	private

		def save_password?
			new_record? || !password.nil?	|| !password_confirmation.nil?
		end

		def encrypt_password
			self.salt = make_salt unless has_password?(password)
			self.encrypted_password = encrypt(password)
		end

		def encrypt(string)
			secure_hash("#{salt}--#{string}")
		end

		def make_salt
			secure_hash("#{Time.now.utc}--#{password}")
		end

		def secure_hash(string)
			Digest::SHA2.hexdigest(string)
		end


end

app/controllers/user/ingredients_controller.rb
class User::IngredientsController < ApplicationController

	before_filter :redirect_if_not_signed_in

	def index
		@created_ingredients = current_user.ingredients
		@consumed_ingredients = current_user.consumed_ingredients.where("logs created_at > ?", 7.days.ago).order("created_at DESC")
		@title = "My Ingredients"
  end

  def create
  end

  def update
  end

  def new
  end

  def edit
  end
end

app/controllers/users/ingredients_controller.rb
class Users::IngredientsController < ApplicationController

	before_filter :redirect_if_not_signed_in

	def index
		@created_ingredients = current_user.ingredients
		@consumed_ingredients = current_user.consumed_ingredients.where("logs created_at > ?", 7.days.ago).order("created_at DESC")
		@title = "My Ingredients"
  end

  def create
  end

  def update
  end

  def new
  end

  def edit
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	include UserHelper

  before_filter :redirect_if_not_signed_in, :only => [:profile, :edit, :update, :destroy]

	def new
		@title = "Sign Up"
		@user = User.new
  end
     def show
		@user = User.find(params[:id])
		@title = @user.name
		
      respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
          end
    end	
    
  def update
		if current_user.update_attributes(user_params)
			redirect_to profile_path
		else
			flash.now[:error] = "Fix the errors before updating"
			@title = "Edit Profile"
			@user = current_user
			render 'edit'
		end
  end

	def profile
			@title = current_user.name
			@user = current_user
			@count = Ingredient.count
			@recentusers = Ingredient.recently_added.group("creator_id")
	end

  def create
		@user = User.create(user_params)
		if @user.save
			sign_in @user
			redirect_to @user
		else
			flash.now[:error] = "Fix the errors before clicking Sign Up"
			@title = "Sign Up"
			render 'new'
		end
  end

  def edit
  	@title = "Edit Profile"
		@user = current_user
		puts @user
	end

  def destroy
		user = current_user
		sign_out
	  user.delete
		redirect_to root_path
  end

  def index
  end

  def remove_log_item
		lr = LogRecipe.find(params[:lrid])
		unless lr.user_id = current_user.id
			redirect_to root_path
		end
		lr.logs.each {|l| l.delete}
		lr.delete
		redirect_to profile_path
	end


end

app/helpers/user/ingredients_helper.rb
module User::IngredientsHelper
end

app/helpers/user_helper.rb
module UserHelper
	def user_params
		params[:user].slice(:name, :email, :password, :password_confirmation)
	end
end

app/views/users/_form.html.erb
<%= form_for @user, :html => { :class => 'form-horizontal' } do |f| %>
  <fieldset>
    <legend><%= controller.action_name.capitalize %> /User</legend>

    <div class="control-group">
      <%= f.label :name, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :name, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :email, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :email, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :encrypted_password, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :encrypted_password, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :salt, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :salt, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :username, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :username, :class => 'text_field' %>
      </div>
    </div>

    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to 'Cancel', users_path, :class => 'btn' %>
    </div>
  </fieldset>
<% end %>

app/views/users/_user_form.html.erb
<%= form_for(user) do |f| %>
	<% unless user.errors.empty? %>
	<div id="user_error_message">
		You have some errors.<br />
		<ul>
		<% user.errors.keys.each do |error_field| %>
			<li><%= "#{error_field.to_s.gsub("_"," ").capitalize} #{user.errors[error_field].first}" %> </li>
		<% end %>
		</ul>
	</div>
	<%end%>
	<div class = "field" >
		<%= f.label :full_name %><br />
		<%= f.text_field :name %>
	</div>
	<div class = "field" >
		<%= f.label :email %><br />
		<%= f.text_field :email %>
	</div>
	<div class = "field" >
		<%= f.label :password %><br />
		<%= f.password_field :password %>
	</div>
	<div class = "field" >
		<%= f.label :password_confirmation %><br />
		<%= f.password_field :password_confirmation %>
	</div>
	<div class = "actions">
		<% button_text ||= "Sign Up!" %>
		<%= f.submit button_text%>
	</div>
<% end %>

app/views/users/edit.html.erb
<div class = "container">
<div class = "content">
<div class = "row">
<div class = "login-form">
<h1>Edit Profile</h1>

<%= link_to "Delete Profile", user_path(current_user), :method => :delete, :confirm => "Are you sure that you want to delete your profile? This action cannot be undone"%>
<%= render :partial => 'user_form', :locals => {:user => @user, :button_text => "Update Profile"} %>
</div>
</div>
</div>
</div>

app/views/users/index.html.erb
<h1>User#index</h1>
<p>Find me in app/views/user/index.html.erb</p>

app/views/users/new.html.erb
<div class = "container">
<div class = "content">
<div class = "row">
<div class = "login-form">

<h1>Create an Account</h1>
 
<%= render :partial => "user_form", :locals => {:user => @user} %>
</div>
</div>
</div>
</div>

app/views/users/profile.html.erb
<h1><%= @user.name %></h1>

<%= link_to "Edit Profile", edit_user_path(current_user) %>
<br>
<br>
<div class="row-fluid">
<% if signed_in? %>
<div class="span4">
<% else %>
<div class="span12">
<% end %>
<div class="hero-unit">
<h2>My Recipes</h2>
<br>


<table class ="table table-striped">
        <thead>
	        <tr>
	        <th></th>
          	</tr>
        </thead>
        
    <%  current_user.recipes.order("created_at DESC").limit(10).each do |recipe| %>
         <tr>
           <td><%= link_to recipe.name.titleize, recipe %>
           <%  recipe.ingredients.each do |ingredient| %>
          <li><%= link_to ingredient.name.titleize, ingredient %></li>
           <% end %>
           <i class="pull-right">Created on <%=  recipe.created_at.strftime('%m/%d/%Y')%></i>
           </td>
        </tr>
<% end %>
</table>


</div>
</div>
<% if signed_in? %>
<div class="span5">
<div class="hero-unit">
<h2>My Nutrition Log <%= link_to "Add A Meal", :ingredients, :class => 'btn btn-success pull-right' %></h2>
<br>

<table class ="table table-striped">
          <thead>
<tr>
	<th>Meal Name</th>
    <th>Consumed At</th>
    <th></th>
    <th></th>
  </tr>
        </thead>
<%  current_user.log_recipes.limit(30).each do |recipe| %>
  <tr>
    <td><%=  Recipe.find(params[:id]=recipe.recipe_id).name.titleize %></td>
    <td><%= recipe.created_at.strftime('%m/%d/%Y %I:%M %p') %></td>
    <td> <%= link_to "View Item",  Recipe.find(params[:id]=recipe.recipe_id), :class => 'btn btn-primary btn-mini pull-right' %></td>
    <td> <%= link_to "Delete",  delete_logged_recipe_path(recipe), :class => 'btn btn-danger btn-mini pull-right' %></td>
  </tr> 
<% end %>
</table>
</table>

<% end %>
</div>
</div>
<% if signed_in? %>
<div class="span3">
<div class="hero-unit">
<h2>Nutrients Consumed Today</h2>
<br>

<table class ="table table-striped">
          <thead>
<tr>
	<th>Nutrient </th>
	<th>Quantity</th>
  </tr>
        </thead>
        <% nuts = current_user.getnuts %>
        <tr>
        <td>Calories</td>
        <td><%= nuts[:Calories]%> mg</td>
        </tr>

 <tr>
        <td>Protein </td>
        <td><%= nuts[:Protein]%> mg</td>
        </tr>
                
        <tr>
        <td>Carbs</td>
        <td><%= nuts[:Carbs]%> mg</td>
        </tr>

        
        <tr>
        <td>Fiber</td>
        <td><%= nuts[:Fiber] %> mg</td>
        </tr>

        
        <tr>
        <td>Trans Fat</td>
        <td><%= nuts[:Trans_Fat]%> mg</td>
        </tr>

        
        <tr>
        <td>Fat</td>
        <td><%= nuts[:Fat]%> mg</td>
        </tr>

        
        <tr>
        <td>Vitamin B6</td>
        <td><%= nuts[:Vitamin_B6]%> mg</td>
        </tr>


        <tr>
        <td>Vitamin B12</td>
        <td><%= nuts[:Vitamin_B12]%> mg</td>
        </tr>
        
        <tr>
        <td>Vitamin C</td>
        <td><%= nuts[:Vitamin_C] %> mg</td>
        </tr>
        
        <tr>
        <td>Vitamin D</td>
        <td><%= nuts[:Vitamin_D] %> mg</td>
        </tr>

     
        <tr>
        <td>Calcium</td>
        <td><%= nuts[:Calcium] %> mg</td>
        </tr>

     
        <tr>
        <td>Potassium</td>
        <td><%= nuts[:Potassium] %> mg</td>
        </tr>
             
        <tr>
        <td>Sodium</td>
        <td><%= nuts[:Sodium] %> mg</td>
        </tr>
             

</table>


<% end %>
</div>
</div>
</div>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>


<br>
<br>
<div class="row-fluid">

<div class="span12">
<div class = "hero-unit">
<h2><%= @user.name %>'s Recipes and Ingredients</h2>
<br>


<table class ="table table-striped">
        <thead>
	        <tr>
	        <th>Recipes and Ingredients</th>
          	</tr>
        </thead>
        
    <% @user.recipes.order("created_at DESC").limit(10).each do |recipe| %>
         <tr>
           <td><%= link_to recipe.name.titleize, recipe %>
                    <%  recipe.ingredients.each do |ingredient| %>
                         <li><%= link_to ingredient.name.titleize, ingredient %></li>
                    <% end %>
           <i class="pull-right">Created on <%=  recipe.created_at.strftime('%m/%d/%Y')%></i>
           </td>
        </tr>
<% end %>
</table>


</div>
</div>
</div>