config/routes.rb
Nl::Application.routes.draw do

	get "/home" => "pages#home", :as => :home
  get "/about" => "pages#about", :as => :about
  get "/team" => "pages#team", :as => :team

	get "/search" => "recipes#search", :as => :recipe_search  
	get "/recipes/:id/consume" => "recipes#consume", :as => :consume_recipe
	get "/remove_log_item/:lrid" => "users#remove_log_item", :as => :delete_logged_recipe
	resources :ingredients, :only => [:index, :show, :new, :create]
	resources :users
	resources :recipes
	get "/ingsearch" => "ingredients#search", :as => :ingredient_search
	get '/recipes/:id/ing/:ingredient_id' => "recipes#addingredient", :as => :ingredient_add
	get '/signup', :to => 'users#new'
	get '/signin', :to => 'sessions#new'
	post '/signin', :to => 'sessions#create'
	get '/signout', :to => 'sessions#destroy'
  match '/profile', :to => 'users#profile'
	root :to => "pages#home"
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
	belongs_to :creator, :class_name => "User"
  has_many :logs, :dependent => :destroy
	has_many :consumers, :class_name => "User", :through => :logs

	has_many :recipe_ingredient_joins

	has_many :recipes,
		:through => :recipe_ingredient_joins

	has_many :nutritions

	validates :name,
		:presence => true

	def self.recently_added
		Ingredient.order("created_at DESC").limit(10)
	end

	def type
		Type.find(self.type_id) if self.type_id
	end

	def type=(ty)
		t = Type.find_by_name(ty)
	  if t.nil?
			t = Type.create({:name => ty})
			self.type_id = t.id
			save
		else
			self.type_id = t.id
			save
		end
	end

	def self.search(search)
      if search
        find(:all, :conditions => ['name LIKE ?', "%#{search}%"], :order => "name ASC")
      else
        find(:all)
      end
    end

end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
	include IngredientHelper

	before_filter :redirect_if_not_signed_in, :only => [:new, :create]

  def index
		@recently_add_ingredients = Ingredient.recently_added
		@title = "Ingredients"
		@recipes = Recipe.search(params[:search])
		if signed_in?
			@created_ingredients = current_user.ingredients
			@consumed_ingredients = current_user.recently_consumed_ingredients
			render "index_user"
		else	
			render "index_public"
		end
  end

  def show
		@ingredient = Ingredient.find(params[:id])
		@title = @ingredient.name
		
		    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @ingredient }
          end
  end

  def new
		@title = "New Ingredient"
		@ingredient = Ingredient.new
  end

  def create
		@ingredient = Ingredient.create(ingredient_params)
		nutr = params[:nutr]
		if @ingredient.save
			@ingredient.nutritions.create({:name => "Calories", :quantity => nutr["Calories"].to_f})
			@ingredient.nutritions.create({:name => "Protein", :quantity => nutr["Protein"].to_f})
			@ingredient.nutritions.create({:name => "Carbs", :quantity => nutr["Carbs"].to_f})
			@ingredient.nutritions.create({:name => "Fiber", :quantity => nutr["Fiber"].to_f})
			@ingredient.nutritions.create({:name => "Trans Fat", :quantity => nutr["Trans_Fat"].to_f})
			@ingredient.nutritions.create({:name => "Fat", :quantity => nutr["Fat"].to_f})
			@ingredient.nutritions.create({:name => "Vitamin B6", :quantity => nutr["Vitamin_B6"].to_f})
			@ingredient.nutritions.create({:name => "Vitamin B12", :quantity => nutr["Vitamin_B12"].to_f})
			@ingredient.nutritions.create({:name => "Vitamin C", :quantity => nutr["Vitamin_C"].to_f})
			@ingredient.nutritions.create({:name => "Vitamin D", :quantity => nutr["Vitamin_D"].to_f})
			@ingredient.nutritions.create({:name => "Calcium", :quantity => nutr["Calcium"].to_f})
			@ingredient.nutritions.create({:name => "Potassium", :quantity => nutr["Potassium"].to_f})
			@ingredient.nutritions.create({:name => "Sodium", :quantity => nutr["Sodium"].to_f})
			redirect_to ingredient_path @ingredient
		else
			flash.now[:error] = "Fix the errors before saving the ingredient"
			render 'new'
		end
  end

  
    def destroy
		
	  Ingredient.find(params[:id]).delete
		redirect_to ingredients_path
  end

	def search
		@a=Ingredient.search(params[:q])
		render :partial => "ingredients/ingredient_list", :locals => {:ingredient => @a, :rid => params[:rid]}
	end

end

app/controllers/user/ingredients_controller.rb
class User::IngredientsController < ApplicationController

	before_filter :redirect_if_not_signed_in

	def index
		@created_ingredients = current_user.ingredients
		@consumed_ingredients = current_user.consumed_ingredients.where("logs created_at > ?", 7.days.ago).order("created_at DESC")
		@title = "My Ingredients"
  end

  def create
  end

  def update
  end

  def new
  end

  def edit
  end
end

app/controllers/users/ingredients_controller.rb
class Users::IngredientsController < ApplicationController

	before_filter :redirect_if_not_signed_in

	def index
		@created_ingredients = current_user.ingredients
		@consumed_ingredients = current_user.consumed_ingredients.where("logs created_at > ?", 7.days.ago).order("created_at DESC")
		@title = "My Ingredients"
  end

  def create
  end

  def update
  end

  def new
  end

  def edit
  end
end

app/helpers/ingredient_helper.rb
module IngredientHelper
	def ingredient_params
		params[:ingredient].slice(:name, :type_id)
	end
end

app/helpers/user/ingredients_helper.rb
module User::IngredientsHelper
end

app/views/ingredients/_ingredient.html.erb
<div id="ingredient_<%=ingredient.id%>">
	
	<br />
	<% if ingredient.creator != 0 %>
		<i>Created by <%= link_to ingredient.creator.name, ingredient.creator %></i>
	<% end %>
</div>

app/views/ingredients/_ingredient_form.html.erb
<%= form_for(ingredient) do |f| %>
	<% unless ingredient.errors.empty? %>
	<div id = "ingredient_error_message">
	You have some errors.<br />
	<ul>
	<% ingredient.errors.keys.each do |error_field| %>
		<li><%= "#{error_field.to_s.gsub("_", " ").capitalize} #{ingredient.errors[error_field].first}" %> </li>
			<% end %>
			</ul>
			</div>
			<% end %>

			<div class = "field" >
				<%= f.label :name %><br />
				<%= f.text_field :name %>
			</div>
            
            <br>
       <div class = "field">
       <label for="Calories">Calories</label><br />
         <input id="Calories" name="nutr[Calories]" size="30" type="text" />
       </div>   
       <br>
       (Note All Measurements Below are in Milligrams)
       <br>
       <br>
       <div class = "field">
       <label for="Protein">Protein</label><br />
         <input id="Protein" name="nutr[Protein]" size="30" type="text" />
       </div> <br>
              <div class = "field">
       <label for="Carbs">Carbs</label><br />
         <input id="Carbs" name="nutr[Carbs]" size="30" type="text" />
       </div> <br>      
        <div class = "field">
       <label for="Fiber">Fiber</label><br />
         <input id="Fiber" name="nutr[Fiber]" size="30" type="text" />
       </div> <br>
               <div class = "field">
       <label for="Trans_Fat">Trans Fat</label><br />
         <input id="Trans_Fat" name="nutr[Trans_Fat]" size="30" type="text" />
       </div> <br>       
     <div class = "field">
       <label for="Fat">Far</label><br />
         <input id="Fat" name="nutr[Fat]" size="30" type="text" />
       </div><br>
       
     <div class = "field">
       <label for="Vitamin_B6">Vitamin B6</label><br />
         <input id="Vitamin_B6" name="nutr[Vitamin_B6]" size="30" type="text" />
       </div><br>
       
       <div class = "field">
       <label for="Vitamin_B12">Vitamin B12</label><br />
         <input id="Vitamin_B12" name="nutr[Vitamin_B12]" size="30" type="text" />
       </div>  <br>
       
     <div class = "field">
       <label for="Vitamin_C">Vitamin C</label><br />
         <input id="Vitamin_C" name="nutr[Vitamin_C]" size="30" type="text" />
       </div>  <br>     
     <div class = "field">
       <label for="Vitamin_D">Vitamin D</label><br />
         <input id="Vitamin_D" name="nutr[Vitamin_D]" size="30" type="text" />
       </div>   <br>    
            <div class = "field">
       <label for="Calcium">Calcium</label><br />
         <input id="Calcium" name="nutr[Calcium]" size="30" type="text" />
       </div> <br>    
            <div class = "field">
       <label for="Potassium">Potassium</label><br />
         <input id="Potassium" name="nutr[Potassium]" size="30" type="text" />
       </div>  <br>   
            <div class = "field">
       <label for="Sodium">Sodium</label><br />
         <input id="Sodium" name="nutr[Sodium]" size="30" type="text" />
       </div>  <br>   
       
       
			<div class = "actions" >
				<%= f.submit "Create Ingredient", :class =>'btn btn-primary' %>
			</div>
		<%end%>
	

app/views/ingredients/create.html.erb
<h1>Ingredient#create</h1>
<p>Find me in app/views/ingredient/create.html.erb</p>

app/views/ingredients/destroy.html.erb
<h1>Ingredient#destroy</h1>
<p>Find me in app/views/ingredient/destroy.html.erb</p>

app/views/ingredients/edit.html.erb
<h1>Ingredient#edit</h1>
<p>Find me in app/views/ingredient/edit.html.erb</p>

app/views/ingredients/index.html.erb
<h1>My ingredients</h1>

<%= link_to "Create a new ingredient", new_ingredient_path %>
<div id="created_ingredients">
	<h2>Ingredients that I created</h2>
	<% @created_ingredients.each do |i| %>
		<%= render :partial => 'ingredient/ingredient', :locals => {:ingredient => i} %>
	<% end %>
</div>


<div id="consumed_ingredients">
	<h2>Ingredients that I've consumed in the past week</h2>
	<% @created_ingredients.each do |i| %>
		<%= render :partial => 'ingredient/ingredient', :locals => {:ingredient => i} %>
	<% end %>
</div>

app/views/ingredients/index_public.html.erb
<h1>Ingredient#index</h1>
<p>Find me in app/views/ingredient/index.html.erb</p>

app/views/ingredients/index_user.html.erb
<script language ="javascript">
	$(function($) { 
		$("#search-button").click(function() {
			replace_with_search();
		});

		$("#search-text").keypress(function(e) {
			var code = (e.keyCode ? e.keyCode : e.which);
			if(code == 13)
			{
				replace_with_search();
			}
		});

		function replace_with_search()
		{
			$("#consumed_ingredients").load("<%= recipe_search_path %>?q=" + $("#search-text").val());
		};
	});	
</script>


<h1>Food</h1>
<br>
<div class = "row-fluid">
<div class = "span2">

<div class="well">
  <h2>Search</h2>
  <input type="text" class="span2" id="search-text" placeholder="Find an Ingredient..."><br>
  <button type="button" class="btn btn-primary " id="search-button">Search</button>
  <br>
  <br>
  <%= link_to "Create a new ingredient", new_ingredient_path, :class => 'btn btn-success' %>
  <br>
  <br>
  <%= link_to "Create a new recipe", new_recipe_path, :class => 'btn btn-success' %>
</div>

</div>
<div class = "span4">
<div class="hero-unit">

<div id="created_ingredients">
	<h2>My Ingredients and Recipes</h2>
	<br>
	
	
<table class ="table table-striped">
        <thead>
	        <tr>
	        <th></th>
	        <th></th>
	                  	</tr>
        </thead>
		<% cu = current_user.recipes.order("created_at DESC").limit(10)%>
		<%= "No recipes found" if cu.empty? %>
		<% cu.each do |recipe| %>
         <tr>
           <td><%= recipe.name.titleize%> (Recipe)</td>
           <td><%= link_to "View Item", recipe, :class => "btn btn-primary btn-mini" %></td>
           <td><%= link_to "Consume", consume_recipe_path(recipe), :class => "btn btn-success btn-mini" %></td>
            
    
        </tr>
        <tr>
         <%  recipe.ingredients.each do |ingredient| %>
         
          <td><%= ingredient.name.titleize %></td>
          <td><%= link_to "View Item", ingredient, :class => "btn btn-primary btn-mini" %></td>
          <td></td>
    
         </tr>
         <% end %>
         
<% end %>
</table>
</div>
</div>
</div>

<div class = "span6">
<div class = "hero-unit">
<div id="consumed_ingredients">
	<h2>Search for recipes on the left hand side...</h2>

</div>
</div>
</div>
</div>

app/views/ingredients/new.html.erb
<div class = "row">
<div class = "center span6 middle offset5">
<div class = "hero-unit">

<h2>Create An Ingredient</h2>

<%= render :partial => "ingredient_form", :locals => {:ingredient => @ingredient} %>


</div>
</div>
</div>

app/views/ingredients/show.html.erb
<h1><%= @ingredient.name.titleize %></h1>
<br>
<br>
<div class="row-fluid">
    <div class="span12">
        <div class ="hero-unit">
        <h2>Nutrients </h2>
        <table class ="table table-striped">
        <thead>
	        <tr>
	        <th>Nutrition Name </th>
	        <th> Quantity</th>
          	</tr>
        </thead>
        
        <%  @ingredient.nutritions.each do |nutrition| %>
         <tr>
           <td><%= nutrition.name.titleize %></td>
           <td><%= nutrition.quantity %>mg</td>
        </tr>
<% end %>
</table>

        </div>
    </div>

</div>

app/views/ingredients/update.html.erb
<h1>Ingredient#update</h1>
<p>Find me in app/views/ingredient/update.html.erb</p>